name: woocommerce
description: Woocommerce SDK for Flutter. The Complete Woo Commerce SDK for
  building Flutter Ecommerce Applications with amazing features.
version: 1.0.1
homepage: https://github.com/RayOkaah/woocommerce.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  flutter_secure_storage: 8.0.0
  http: ^0.13.6
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.4.0
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.5.4

flutter: null
